In [1]:
from scipy.stats import pearsonr

In [2]:
pearsonr([1,2,3],[1,2,3.1])

(0.99962228516121843, 0.017498096813278487)

In [3]:
pearsonr([1,2,3],[1,20,6])

(0.25383654128340477, 0.83661493668227427)

In [4]:
import scipy.stats

In [5]:
scipy.stats.entropy([0,1],base=2)

0.0

In [6]:
from sklearn.feature_selection import RFE

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
from sklearn.datasets import make_classification

In [9]:
X,y=make_classification(n_samples=100,n_features=10,n_informative=3,random_state=0)

In [10]:
clf=LogisticRegression()

In [11]:
clf.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
selector=RFE(clf,n_features_to_select=3)

In [13]:
selector=selector.fit(X,y)

In [14]:
selector.support_

array([False,  True, False,  True,  True, False, False, False, False, False], dtype=bool)

In [15]:
selector.ranking_

array([7, 1, 4, 1, 1, 3, 2, 8, 6, 5])

In [16]:
import numpy as np

In [17]:
x1=np.arange(0,10,.2)

In [18]:
x1

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [19]:
x2=x1+np.random.normal(loc=0,scale=1,size=len(x1))

In [20]:
x2

array([ -2.38602923,  -0.90176886,  -1.29173513,   0.900141  ,
        -0.33318389,   0.90787189,   0.57860238,   0.26626488,
         1.06002204,   2.20843458,  -0.5452199 ,   1.39245223,
         2.17574367,   2.66401059,   1.67308415,   0.98163429,
         2.84090251,   5.52947108,   2.69516598,   2.77872719,
         2.70407969,   5.82424421,   3.70103537,   4.11382003,
         5.69624351,   6.27047374,   5.05711989,   5.73447674,
         5.79032166,   6.88974195,   5.54047523,   3.87780964,
         7.37538453,   5.87889345,   6.23476611,   8.55549602,
         6.35495187,   7.40604948,   7.18824453,   7.03257142,
         7.13591714,  10.55365923,   8.32848805,   8.56532167,
         8.2676354 ,   9.97272446,   8.57331412,   9.7882717 ,
         9.11857875,   9.17631808])

In [21]:
X=np.c_[(x1,x2)]

In [22]:
X.shape

(50, 2)

In [23]:
good=(x1>5)|(x2>5)

In [24]:
bad=~good

In [25]:
good.shape

(50,)

In [26]:
from sklearn import linear_model,decomposition,datasets

In [27]:
pca=decomposition.PCA()

In [28]:
Xtrans=pca.fit_transform(X)

In [29]:
pca.explained_variance_ratio_

array([ 0.97735553,  0.02264447])

In [30]:
from sklearn import lda

//anaconda/lib/python2.7/site-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)


In [31]:
lda_inst=lda.LDA(n_components=1)

In [32]:
good=x1>x2

In [33]:
Xtrans=lda_inst.fit_transform(X,good)

In [36]:
X=np.c_[np.ones(5),2*np.ones(5),10*np.ones(5)].T

In [37]:
X

array([[  1.,   1.,   1.,   1.,   1.],
       [  2.,   2.,   2.,   2.,   2.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [38]:
from sklearn import manifold

In [39]:
mds=manifold.MDS(n_components=3)

In [41]:
Xtrans=mds.fit_transform(X)

In [42]:
Xtrans

array([[ 4.5202676 , -3.4899353 , -4.59104144],
       [ 3.35512803, -1.50988733, -3.97035464],
       [-7.87539564,  4.99982264,  8.56139608]])